server:
  domains:
    canonical:
      - "file.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
