server:
  domains:
    canonical:
      - "file.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    file:
      enabled: false
      shared: true
    dashboard:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
