FROM {{ MOODLE_IMAGE }}:{{ MOODLE_VERSION }}

{% if MOODLE_OIDC_ENABLED | bool %}
RUN install_packages unzip curl jq \
 && VERSION=$(curl -s https://api.github.com/repos/microsoft/moodle-auth_oidc/tags \
      | jq -r '.[].name' \
      | grep v{{ MOODLE_VERSION }} \
      | sort -Vr \
      | head -n1) \
 && echo "Using version $VERSION" \
 && curl -L -o /tmp/oidc.zip https://github.com/microsoft/moodle-auth_oidc/archive/refs/tags/${VERSION}.zip \
 && unzip /tmp/oidc.zip -d /tmp \
 && mv /tmp/moodle-auth_oidc-* {{ BITNAMI_OIDC_PLUGIN_DIR }} \
 && chown -R {{ BITNAMI_USER_GROUP }} {{ BITNAMI_OIDC_PLUGIN_DIR }} \
 && rm -rf /tmp/oidc.zip
{% endif %}
