galaxy_info:
  author: Kevin Veen-Birchenbach
  description: Installs VLC, libaacs and libbluray for Blu-ray playback on Arch Linux–based systems.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: Kevin Veen-Birchenbach Consulting & Coaching Solutions https://www.veen.world
  galaxy_tags:
    - vlc
    - bluray
    - media
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
  platforms:
    - name: Archlinux
      versions:
        - all
dependencies:
  - dev-java
