csp:
  flags:
    script-src-elem:
      unsafe-inline: true
      unsafe-eval: true
    script-src-attr:
      unsafe-eval: true
  whitelist:
    connect-src:
    - espo.crm.{{ DOMAIN_PRIMARY }}
    - 'data:'
    frame-src:
    - https://s.espocrm.com/
    frame-ancestors:
    - '{{ DOMAIN_PRIMARY }}'
    - '*.{{ DOMAIN_PRIMARY }}'
domains:
  aliases: []
  canonical:
  - espo.crm.{{ DOMAIN_PRIMARY }}
networks:
  local:
    subnet: 192.168.103.64/28
