csp:
  flags:
    style-src-attr:
      unsafe-inline: true
    script-src-elem:
      unsafe-inline: true
  whitelist:
    font-src:
    - http://forum.{{ DOMAIN_PRIMARY }}
domains:
  canonical:
  - forum.{{ DOMAIN_PRIMARY }}
  aliases: []
networks:
  local:
    subnet: 192.168.102.208/28
