csp:
  flags:
    style-src-attr:
      unsafe-inline: true
    script-src-elem:
      unsafe-inline: true
  whitelist:
    font-src:
    - "{{ lookup('tls', 'web-app-discourse', 'url.base') }}"
domains:
  canonical:
  - forum.{{ DOMAIN_PRIMARY }}
  aliases: []
networks:
  local:
    subnet: 192.168.102.208/28
