---
- name: "Ensure compose directory exists for {{ application_id }}"
  ansible.builtin.file:
    path: "{{ lookup('container', application_id, 'files.compose') | dirname }}"
    state: directory
    mode: "0755"

- name: "Render compose.yml for {{ application_id }}"
  ansible.builtin.template:
    src: "compose.yml.j2"
    dest: "{{ lookup('container', application_id, 'files.compose') }}"
    mode: "0640"
  notify: compose up

- name: "Ensure env directory exists for {{ application_id }}"
  ansible.builtin.file:
    path: "{{ lookup('container', application_id, 'files.env') | dirname }}"
    state: directory
    mode: "0755"

- name: "Render env for {{ application_id }}"
  ansible.builtin.template:
    src: "env.j2"
    dest: "{{ lookup('container', application_id, 'files.env') }}"
    mode: "0640"
  notify: compose up

- name: "load docker, db and proxy for {{ application_id }}"
  include_role:
    name: sys-stk-full
  vars:
    docker_compose_flush_handlers: true

- name: "Run Decidim setup routines"
  include_tasks: 01_setup.yml

