---
galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Deploys pgAdmin, a web-based PostgreSQL administration tool with multi-server management, configurable settings, and optional OAuth2 integration.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - pgadmin
    - docker
    - webui
    - oauth2
    - postgresql
  issue_tracker_url: https://s.infinito.nexus/issues
