oidc:
  enabled: "{{ 'web-app-keycloak' in group_names }}"
  shared: "{{ 'web-app-keycloak' in group_names }}"
logout:
  enabled: "{{ 'web-svc-logout' in group_names }}"
  shared: "{{ 'web-svc-logout' in group_names }}"
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
email:
  enabled: "{{ 'web-app-mailu' in group_names }}"
  shared: "{{ 'web-app-mailu' in group_names }}"
mariadb:
  enabled: true  # nocheck: dynamic-flag
  shared: "{{ 'svc-db-mariadb' in group_names }}"
moodle:
  # nocheck: docker-version
  version: '4.5'  # Latest LTS - Necessary for OIDC
  image: bitnamilegacy/moodle
  name: moodle
  min_storage: 10GB
  cpus: 1.0
  mem_reservation: 1g
  mem_limit: 2g
  pids_limit: 512
  site_titel: Academy on {{ DOMAIN_PRIMARY }}
  ports:
    local:
      http: 8026
  run_after:
  - web-app-keycloak
  lifecycle: beta
# nocheck: dynamic-flag
css:
  enabled: false
  shared: true
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
