galaxy_info:
  author: Alejandro Roman Ibanez
  description: Unite your team with Mattermost, an open-source, self-hosted messaging platform that delivers secure, real-time collaboration through channels, threads, and integrations — keeping your conversations private and under your control.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: 'Kevin Veen-Birkenbach

    Consulting & Coaching Solutions

    https://www.veen.world

    '
  galaxy_tags:
    - mattermost
    - docker
    - messaging
    - team-chat
    - collaboration
    - self-hosted
  issue_tracker_url: https://s.infinito.nexus/issues
dependencies: []
