galaxy_info:
  author: Kevin Veen-Birkenbach
  description: FusionDirectory is a web-app-based tool to manage LDAP directories and this role ensures a reliable, easy-to-use interface for LDAP administration.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: Kevin Veen-Birkenbach Consulting & Coaching Solutions
  min_ansible_version: '2.9'
  platforms:
    - name: Docker
      versions:
        - latest
  galaxy_tags:
    - fusiondirectory
    - ldap
    - docker
    - administration
  issue_tracker_url: https://s.infinito.nexus/issues
