galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Utility role providing shared task helpers for frontend service loading.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: 'Kevin Veen-Birkenbach

    Consulting & Coaching Solutions

    https://www.veen.world

    '
  min_ansible_version: '2.9'
  platforms:
    - name: Linux
      versions:
        - all
  galaxy_tags:
    - services
    - utils
    - infinito
  issue_tracker_url: https://s.infinito.nexus/issues
dependencies: []
