---
- name: "load docker, proxy for '{{ application_id }}'"
  include_role:
    name: sys-stk-full
  vars:
    compose_handlers_flush: true
    compose_repository_pull: false

- include_tasks: utils/once/flag.yml
