- name: "Check if {{ service_key }} endpoint is reachable"
  uri_probe:
    url: "{{ lookup('tls', service_role, 'url.base') }}"
    validate_certs: yes
    status_code: 200
  register: _frontend_service_reachability
  failed_when: false
  changed_when: false

- name: "Load {{ service_key }} (Once)"
  include_tasks: "utils/load_app.yml"
  when: (_frontend_service_reachability.status | default(0) | int) != 200
  vars:
    load_app_id: "{{ service_role }}"

- name: "Flush handlers after loading {{ service_key }}"
  meta: flush_handlers
