---
TEST_E2E_PLAYWRIGHT_IMAGE: "{{ lookup('image', 'test-e2e-playwright', 'playwright', 'ref') }}"
TEST_E2E_PLAYWRIGHT_VERSION: "{{ lookup('image', 'test-e2e-playwright', 'playwright', 'version') | image_version }}"
TEST_E2E_PLAYWRIGHT_APPS: >-
  {{
    playbook_dir
    | discover_playwright_roles(
        only_roles=TEST_E2E_PLAYWRIGHT_ONLY_ROLES,
        skip_roles=TEST_E2E_PLAYWRIGHT_SKIP_ROLES
      )
  }}
