galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Deploys phpMyAdmin, a web-based administration tool for MySQL/MariaDB databases, providing schema management, querying, and import/export.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  min_ansible_version: '2.9'
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - phpmyadmin
    - docker
    - webui
    - oauth2
    - mariadb
    - postgresql
  issue_tracker_url: https://s.infinito.nexus/issues
