---
- name: Install & configure OIDC plugin (if enabled)
  include_tasks: setup/oidc.yml
  when: SHOPWARE_OIDC_ENABLED | bool

- name: Install & configure LDAP plugin (if enabled)
  include_tasks: setup/ldap.yml
  when: SHOPWARE_LDAP_ENABLED | bool
