- name: Remove OIDC plugin if disabled
  include_tasks: cleanup/oidc.yml
  when: not (SHOPWARE_OIDC_ENABLED | bool)

- name: Remove LDAP plugin if disabled
  include_tasks: cleanup/ldap.yml
  when: not (SHOPWARE_LDAP_ENABLED | bool)
