---
- name: Set default compose_repository_path
  set_fact:
    compose_repository_path: "{{ [ lookup('container', application_id, 'directories.services'), 'repository/' ] | path_join }}"

- name: Pull docker repository
  git:
    repo: "{{ compose_repository_url }}"
    dest: "{{ compose_repository_path }}"
    version: "{{ compose_repository_ref | default('main') }}"
    single_branch: true
    depth: 1
    update: true
    recursive: true
    force: true
    accept_hostkey: true
  register: docker_repo_pull
  retries: 12
  delay: 30
  until: docker_repo_pull is succeeded
  notify:
    - compose build
    - compose up
  become: true
