---
galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Automates the cleanup of old backups by executing a Python script that deletes outdated backup versions when disk usage exceeds a specified
    threshold.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - backup
    - cleanup
    - disk
    - automation
  issue_tracker_url: https://s.infinito.nexus/issues
