galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Create Cloudflare wildcard DNS records (*.parent) for parent hosts; no base or *.apex records.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  min_ansible_version: '2.12'
  galaxy_tags:
    - dns
    - cloudflare
    - automation
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
dependencies: []
