galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Detects anonymous Docker volumes not bound to containers (unless whitelisted) and alerts.
  company: "Kevin Veen-Birkenbach  \nConsulting & Coaching Solutions  \nhttps://www.veen.world\n"
  license: Infinito.Nexus Community License (Non-Commercial)
  min_ansible_version: '2.9'
  platforms:
    - name: Archlinux
      versions:
        - rolling
  galaxy_tags:
    - monitor
    - docker
    - volumes
    - health
    - systemd
