galaxy_info:
  author: Kevin Veen-Birchenbach
  description: Serves static assets via Nginx by copying from a source directory to the Nginx data path.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: Kevin Veen-Birchenbach Consulting & Coaching Solutions https://www.veen.world
  galaxy_tags:
    - assets
    - nginx
    - static
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
  platforms:
    - name: Any
      versions:
        - all
