asset:
  enabled: true
  shared: true
  cpus: '0.2'
  mem_reservation: 128m
  mem_limit: 256m
  pids_limit: 128
  source_directory: '{{ playbook_dir }}/assets'
  url: //{{ lookup('domain', 'web-svc-file') }}/assets
  run_after:
  - web-svc-file
  lifecycle: beta
file:
  enabled: "{{ 'web-svc-file' in group_names }}"
  shared: "{{ 'web-svc-file' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
# nocheck: dynamic-flag
css:
  enabled: false
  shared: false
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
