- name: "MEDIAWIKI | Bootstrap DB (install if empty) then update"
  script: >-
    install_or_update.sh
    "{{ MEDIAWIKI_NETWORK_DATABASE }}" "{{ lookup('database', application_id, 'version') | default('latest') }}"
    "{{ lookup('database', application_id, 'host') }}" "{{ lookup('database', application_id, 'port') }}"
    "{{ lookup('database', application_id, 'username') }}" "{{ lookup('database', application_id, 'password') }}"
    "{{ lookup('database', application_id, 'name') }}"
    "{{ MEDIAWIKI_USER }}" "{{ MEDIAWIKI_IMAGE }}" "{{ MEDIAWIKI_VERSION }}" "{{ MEDIAWIKI_HTML_DIR }}"
    "{{ MEDIAWIKI_URL }}" "{{ MEDIAWIKI_SITENAME }}"
    "{{ MEDIAWIKI_ADMINISTRATOR_NAME }}" "{{ MEDIAWIKI_ADMINISTRATOR_PASSWORD }}"
    "{{ MEDIAWIKI_CONTAINER }}"
  changed_when: false
  no_log: "{{ MASK_CREDENTIALS_IN_LOGS | bool }}"
