galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Jira Software is Atlassian’s issue & project tracking platform. This role deploys Jira in Docker, adds optional OIDC support, and integrates with the Infinito.Nexus ecosystem.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: 'Kevin Veen-Birkenbach

    Consulting & Coaching Solutions

    https://www.veen.world

    '
  galaxy_tags:
    - jira
    - project management
  issue_tracker_url: https://s.infinito.nexus/issues
dependencies: []
