logout:
  enabled: "{{ 'web-svc-logout' in group_names }}"
  shared: "{{ 'web-svc-logout' in group_names }}"
# nocheck: dynamic-flag
# noqa: oidc
oidc:
  enabled: false
  shared: false
# nocheck: dynamic-flag
# noqa: oauth2
oauth2:
  enabled: false
  shared: false
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
email:
  enabled: "{{ 'web-app-mailu' in group_names }}"
  shared: "{{ 'web-app-mailu' in group_names }}"
postgres:
  enabled: true  # nocheck: dynamic-flag
  shared: "{{ 'svc-db-postgres' in group_names }}"
jira:
  image: atlassian/jira-software
  version: latest
  name: jira
  min_storage: 20GB
  cpus: '2.0'
  mem_reservation: 4g
  mem_limit: 6g
  pids_limit: 2048
  ports:
    local:
      http: 8015
  run_after:
  - web-app-matomo
  - web-app-mailu
  lifecycle: unsupported
# nocheck: dynamic-flag
css:
  enabled: true
  shared: true
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
