oidc:
  enabled: "{{ 'web-app-keycloak' in group_names }}"
  shared: "{{ 'web-app-keycloak' in group_names }}"
logout:
  enabled: "{{ 'web-svc-logout' in group_names }}"
  shared: "{{ 'web-svc-logout' in group_names }}"
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
minio:
  backup:
    no_stop_required: false
  image: quay.io/minio/minio
  version: latest
  name: minio
  min_storage: 20GB
  cpus: '2.0'
  mem_reservation: 2g
  mem_limit: 4g
  pids_limit: 2048
  run_after:
  - web-app-keycloak
  - web-app-matomo
  lifecycle: beta
# nocheck: dynamic-flag
redis:
  backup:
    disabled: true
  enabled: false
# nocheck: dynamic-flag
css:
  enabled: true
  shared: true
# nocheck: dynamic-flag
javascript:
  enabled: false
  shared: true
ollama:
  enabled: "{{ 'svc-ai-ollama' in group_names }}"
  shared: "{{ 'svc-ai-ollama' in group_names }}"
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
api:
  ports:
    local:
      http: 8057
console:
  ports:
    local:
      http: 8058
