- name: "SYS-STK-BACKEND | Compute load flag for '{{ service_id }}' (enabled && shared)"
  ansible.builtin.set_fact:
    load_service: >-
      {{
        query(
          'service_should_load',
          service_id,
          application_id=application_id,
          service_name=service_name,
          default=False
        ) | first
      }}

- name: "SYS-STK-BACKEND | Load '{{ service_id }}' (Once)"
  ansible.builtin.include_tasks: "utils/load_app.yml"
  vars:
    load_app_id: "{{ service_id }}"
  when: load_service | bool
