---
- name: "load docker, proxy for '{{ application_id }}'"
  include_role:
    name: sys-stk-full
  vars:
    compose_handlers_flush: true
    compose_repository_url: "{{ ROULETTE_REPOSITORY }}"
    compose_repository_pull: true
    compose_repository_ref: "{{ ROULETTE_REF }}"
