galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Injects a custom JavaScript snippet into Nginx-served HTML responses via sub_filter.
  company: "Kevin Veen-Birkenbach  \nConsulting & Coaching Solutions  \nhttps://www.veen.world\n"
  license: Infinito.Nexus Community License (Non-Commercial)
  min_ansible_version: '2.9'
  platforms:
    - name: Archlinux
      versions:
        - rolling
  galaxy_tags:
    - nginx
    - javascript
    - csp
    - sub_filter
    - injection
    - global
  issue_tracker_url: https://s.infinito.nexus/issues
