oidc:
  enabled: false
  shared: false
logout:
  enabled: false
  shared: false
dashboard:
  enabled: true
  shared: true
matomo:
  enabled: true
  shared: true
application:
  image: python
  version: 3.14-bookworm
  name: web-app-bridgy-fed
  repository: https://github.com/snarfed/bridgy-fed.git
  branch: main
  min_storage: 5GB
  cpus: '0.5'
  mem_reservation: 256m
  mem_limit: 1g
  pids_limit: 512
css:
  enabled: true
  shared: true
# noqa: email
email:
  enabled: false
  shared: false
prometheus:
  enabled: true
  shared: true
bridgy-fed:
  ports:
    local:
      http: 8053
  lifecycle: beta
  min_storage: 1GB
  cpus: '0.2'
  mem_reservation: 128m
  mem_limit: 256m
  pids_limit: 256
