# nocheck: dynamic-flag
# nocheck: logout
logout:
  enabled: false
  shared: false
# nocheck: dynamic-flag
# nocheck: oidc
oidc:
  enabled: false
  shared: false
# nocheck: dynamic-flag
# nocheck: oauth2
oauth2:
  enabled: false
  shared: false
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
application:
  image: python
  version: 3.14-bookworm
  name: web-app-bridgy-fed
  repository: https://github.com/snarfed/bridgy-fed.git
  branch: main
# nocheck: dynamic-flag
css:
  enabled: true
  shared: true
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
bridgy-fed:
  ports:
    local:
      http: 8053
  lifecycle: beta
