galaxy_info:
  author: Kevin Veen-Birchenbach
  description: Installs Jrnl CLI journal application on Pacman-based systems for command-line journaling.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: Kevin Veen-Birchenbach Consulting & Coaching Solutions https://www.veen.world
  galaxy_tags:
    - jrnl
    - journal
    - cli
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
  platforms:
    - name: Archlinux
      versions:
        - all
dependencies: []
