galaxy_info:
  author: Kevin Veen-Birkenbach
  description: 'LittleJS Playground – self-hosted LittleJS example browser and collection of HTML5 games and demos, wrapped as a Dockerized web app.

    '
  license: Infinito.Nexus Community License (Non-Commercial)
  company: 'Kevin Veen-Birkenbach

    Consulting & Coaching Solutions

    https://www.veen.world

    '
  galaxy_tags:
    - infinito
    - docker
    - webapp
    - game
    - html5
    - littlejs
  issue_tracker_url: https://s.infinito.nexus/issues
dependencies: []
