---
galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Wrapper role to install AUR packages via kewlfft.aur.aur using yay.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - aur
    - yay
    - archlinux
    - package-management
    - wrapper
  issue_tracker_url: https://s.infinito.nexus/issues
