FROM {{ SIMPLEICONS_IMAGE }}:{{ SIMPLEICONS_VERSION }} AS builder

WORKDIR /app
COPY ./config/package*.json ./

RUN npm install

FROM {{ SIMPLEICONS_IMAGE }}:{{ SIMPLEICONS_VERSION }}

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY ./config/server.js .

EXPOSE {{ container_port }}

CMD ["node", "server.js"]
