domains:
  canonical:
    - open.talk.{{ DOMAIN_PRIMARY }}
  aliases: []
csp:
  flags:
    style-src-attr:
      unsafe-inline: true
    script-src-elem:
      unsafe-inline: true
    script-src-attr:
      unsafe-inline: true
  whitelist:
    connect-src:
      - "{{ lookup('tls', 'web-app-keycloak', 'url.base') }}"
      - "{{ lookup('domain', 'web-app-opencloud') }}"
      - 'wss:'
    frame-src:
      - "{{ lookup('tls', 'web-app-keycloak', 'url.base') }}"
    media-src:
      - 'blob:'
      - '*'
    worker-src:
      - 'blob:'
networks:
  local:
    subnet: 192.168.105.64/28
