application_id: drv-intel

# Package name differs across distributions:
# - Arch Linux: intel-media-driver
# - Debian/Ubuntu: intel-media-va-driver
# - Fedora: libva-intel-media-driver
# - CentOS Stream 9: libva-intel-hybrid-driver (via EPEL)
DRV_INTEL_PACKAGES_BY_DISTRIBUTION:
  Archlinux:
    - intel-media-driver
  Debian:
    - intel-media-va-driver
  Ubuntu:
    - intel-media-va-driver
  Fedora:
    - libva-intel-media-driver
  CentOS:
    - libva-intel-hybrid-driver
  CentOS Stream:
    - libva-intel-hybrid-driver
