- block:
    - ansible.builtin.systemd:
        name: "{{ sys_svc_sshd_service_unit }}"
        state: restarted
        enabled: true
        daemon_reload: true
  rescue:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/utils/rescue_ssh_restart.yml"
