galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Deploys Matrix, a decentralized communication platform for secure, real-time messaging and collaboration with federation, end-to-end encryption, and protocol bridges.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  galaxy_tags:
    - matrix
    - docker
    - federated
    - decentralized
    - real-time
    - encrypted
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
dependencies: []
