oidc:
  enabled: true
  shared: true
logout:
  enabled: true
  shared: true
dashboard:
  enabled: true
  shared: true
matomo:
  enabled: false
  shared: false
email:
  enabled: true
  shared: true
postgres:
  enabled: true
  shared: true
synapse:
  version: latest
  image: matrixdotorg/synapse
  name: matrix-synapse
  backup:
    no_stop_required: true
  ports:
    local:
      http: 8021
    public:
      federation: 8448
  min_storage: 10GB
  cpus: '1.0'
  mem_reservation: 1g
  mem_limit: 2g
  pids_limit: 1024
element:
  version: latest
  image: vectorim/element-web
  name: matrix-element
  ports:
    local:
      http: 8022
  min_storage: 1GB
  cpus: '0.2'
  mem_reservation: 128m
  mem_limit: 256m
  pids_limit: 256
matrix-chatgpt-bot:
  version: latest
  image: ghcr.io/matrixgpt/matrix-chatgpt-bot
  min_storage: 1GB
  cpus: '0.2'
  mem_reservation: 128m
  mem_limit: 256m
  pids_limit: 256
css:
  enabled: true
  shared: true
prometheus:
  enabled: true
  shared: true
  native_metrics:
    enabled: true
    port: 9000
    service_key: synapse
  communication:
    channel: true
matrix:
  playbook_tags: setup-all,start
  server_name: '{{ DOMAIN_PRIMARY }}'
  setup: false
  plugins:
    chatgpt: false
    facebook: false
    immesage: false
    instagram: false
    signal: false
    slack: false
    telegram: false
    whatsapp: false
  run_after:
    - web-app-matomo
    - web-app-keycloak
    - web-app-mailu
  lifecycle: beta
