galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Provides a Docker Compose snippet for a Memcached service (`memcached`) with optional volume, healthcheck, and logging.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: 'Kevin Veen-Birkenbach

    Consulting & Coaching Solutions

    https://www.veen.world

    '
  galaxy_tags:
    - memcached
    - docker
    - cache
  issue_tracker_url: https://s.infinito.nexus/issues
dependencies: []
