---
memcached:
  image: memcached
  version: latest
  min_storage: 1GB
  backup:
    disabled: true
  lifecycle: pre-alpha
  cpus: "0.25"
  mem_reservation: "64m"
  mem_limit: "256m"
  pids_limit: 256
