# nocheck: dynamic-flag
logout:
  enabled: false
  shared: false
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
# nocheck: dynamic-flag
redis:
  enabled: false
  backup:
    disabled: true
mig:
  image: ghcr.io/kevinveenbirkenbach/infinito-mig
  version: latest
  name: mig
  min_storage: 1GB
  ports:
    inter: 80
    local:
      http: 8047
  lifecycle: alpha
# nocheck: dynamic-flag
css:
  enabled: true
  shared: true
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
