galaxy_info:
  author: Kevin Veen-Birchenbach
  description: Stub role for deploying an XMPP server/container—implementation pending.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: Kevin Veen-Birchenbach Consulting & Coaching Solutions https://www.veen.world
  galaxy_tags:
    - xmpp
    - chat
    - stub
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
  platforms:
    - name: Any
      versions:
        - all
dependencies: []
