logout:
  enabled: false
  shared: false
prometheus:
  enabled: true
  shared: true
oidc:
  enabled: false
  shared: false
ldap:
  enabled: true
  shared: true
xmpp:
  image: ejabberd/ecs
  version: latest
  name: ejabberd
  ports:
    local:
      http: 8082
  run_after:
  - svc-db-openldap
  lifecycle: beta
