logout:
  enabled: false
  shared: false
prometheus:
  enabled: true
  shared: true
oidc:
  enabled: false
  shared: false
ldap:
  enabled: true
  shared: false
xmpp:
  image: ejabberd/ecs
  version: latest
  name: ejabberd
  ports:
    local:
      http: 8082
  run_after:
    - web-app-keycloak
    - svc-db-openldap
  lifecycle: beta
  min_storage: 5GB
  cpus: '0.5'
  mem_reservation: 256m
  mem_limit: 1g
  pids_limit: 512
