galaxy_info:
  author: Kevin Veen-Birchenbach
  description: Deploys a SocialHome federated social network via Docker Compose with basic domain wiring.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: Kevin Veen-Birchenbach Consulting & Coaching Solutions https://www.veen.world
  galaxy_tags:
    - socialhome
    - social
    - federated
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
  platforms:
    - name: Any
      versions:
        - all
