socialhome:
  lifecycle: pre-alpha
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
# nocheck: dynamic-flag
logout:
  enabled: false
