# General 
application_id:                 "web-app-taiga"
js_application_name:            "Taiga"
entity_name:                    "{{ application_id | get_entity_name }}"

# Taiga      

## General
TAIGA_EMAIL_BACKEND:            "{{ 'smtp' if SYSTEM_EMAIL_SMTP else 'console' }}"  ## use an SMTP server or display the emails in the console (either "smtp" or "console")

## User
TAIGA_SUPERUSER_NAME:           "{{ users.administrator.username }}"
TAIGA_SUPERUSER_PASSWORD:       "{{ users.administrator.password }}"
TAIGA_SUPERUSER_EMAIL:          "{{ users.administrator.email }}"

## Authentication
TAIGA_OIDC_ENABLED:             "{{ lookup('config', application_id, 'compose.services.oidc.enabled') }}"
TAIGA_LDAP_ENABLED:             "{{ lookup('config', application_id, 'compose.services.ldap.enabled', false) }}"
TAIGA_PLUGINS_ENABLED:          "{{ TAIGA_OIDC_ENABLED | bool or TAIGA_LDAP_ENABLED | bool }}"

## Docker
TAIGA_COMPOSE_INIT_PATH:        "{{ [ lookup('container', application_id, 'directories.instance'),'compose-inits.yml' ] | path_join }}"
TAIGA_DOCKER_IMAGE_BACKEND:     "taigaio/taiga-back"
TAIGA_DOCKER_IMAGE_FRONTEND:    "taigaio/taiga-front"
TAIGA_DOCKER_IMAGE_FRONTEND_OIDC: "{{ entity_name }}-front-oidc:{{ TAIGA_VERSION }}"
TAIGA_FRONTEND_CONF_PATH:       "{{ [ lookup('container', application_id, 'directories.config'),'conf.json' ] | path_join }}"
TAIGA_VERSION:                  "{{ lookup('config', application_id, 'compose.services.taiga.version') }}"

### Backend
TAIGA_SERVICE:                  "{{ entity_name }}"
TAIGA_HOSTNAME:                 "taiga-back"
TAIGA_CONTAINER:                "{{ entity_name }}"
TAIGA_VOLUME_MEDIA:             "/taiga-back/media"
TAIGA_VOLUME_STATIC:            "/taiga-back/static"

## Services 
TAIGA_MANAGER_SERVICE:          "manager"
TAIGA_ASYNC_SERVICE:            "async"
TAIGA_ASYNC_RABBITMQ_SERVICE:   "async-rabbitmq"
TAIGA_EVENTS_RABBITMQ_SERVICE:  "events-rabbitmq"
TAIGA_FRONT_SERVICE:            "front"
TAIGA_EVENTS_SERVICE:           "events"

