galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Prepares and manages the CDN folder structure with shared, vendor, and per-role release directories.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    Consulting & Coaching Solutions
    https://www.veen.world
  min_ansible_version: '2.9'
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - cdn
    - nginx
    - assets
    - roles
    - versioning
  issue_tracker_url: https://s.infinito.nexus/issues
