# General
application_id:           "svc-net-pihole"

# Pi-hole
# https://pi-hole.net/
PIHOLE_VERSION:           "{{ lookup('config', application_id, 'compose.services.pihole.version') }}"
PIHOLE_IMAGE:             "{{ lookup('config', application_id, 'compose.services.pihole.image') }}"
PIHOLE_CONTAINER:         "{{ lookup('config', application_id, 'compose.services.pihole.name') }}"
PIHOLE_PORT:              "{{ lookup('config', application_id, 'compose.services.pihole.port') }}"
PIHOLE_VOLUME_DATA:       "{{ lookup('config', application_id, 'compose.volumes.data') }}"
PIHOLE_VOLUME_DNSMASQ:    "{{ lookup('config', application_id, 'compose.volumes.dnsmasq') }}"
PIHOLE_NETWORK:           "{{ lookup('config', application_id, 'compose.network') }}"
PIHOLE_UPSTREAM_DNS:      "{{ lookup('config', application_id, 'pihole.upstream_dns') }}"
PIHOLE_TIMEZONE:          "{{ lookup('config', application_id, 'pihole.timezone') }}"
PIHOLE_PASSWORD:          "{{ lookup('password', application_id, 'admin') }}"
