source_directory: "{{ playbook_dir }}/assets"
url:              "//<< defaults_applications['web-svc-file']server.domains.canonical[0] >>/assets"
server:
  domains:
    canonical:
      - asset.{{ DOMAIN_PRIMARY }}
    aliases: []
compose:
  services:
    asset:
      enabled: false
      shared: true
    matomo:
      enabled: true
      shared: true
    css:
      enabled: false
      shared: false
