galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Configures Nginx to serve sites securely over HTTPS, integrates Let’s Encrypt and cleans up stale domain configs.
  company: "Kevin Veen-Birkenbach  \nConsulting & Coaching Solutions  \nhttps://www.veen.world\n"
  license: Infinito.Nexus Community License (Non-Commercial)
  min_ansible_version: '2.9'
  platforms:
    - name: Archlinux
      versions:
        - rolling
  galaxy_tags:
    - nginx
    - https
    - tls
    - letsencrypt
    - security
    - automation
  issue_tracker_url: https://s.infinito.nexus/issues
