domains:
  canonical:
  - collabora.{{ DOMAIN_PRIMARY }}
  aliases: []
csp:
  whitelist:
    frame-ancestors:
    - '*.{{ DOMAIN_PRIMARY }}'
  flags:
    style-src-attr:
      unsafe-inline: true
networks:
  local:
    subnet: 192.168.103.96/28
