csp:
  flags:
    script-src-attr:
      unsafe-eval: true
  whitelist:
    manifest-src: auth.{{ DOMAIN_PRIMARY }}
domains:
  aliases: []
  canonical:
  - suite.crm.{{ DOMAIN_PRIMARY }}
networks:
  local:
    subnet: 192.168.104.112/28
