galaxy_info:
  author: Prageeth Panicker
  description: Deploy Decidim, an open-source participatory democracy platform for public consultations, civic processes, community voting, and collaborative policy creation.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: 'Kevin Veen-Birkenbach

    Consulting & Coaching Solutions

    https://www.veen.world

    '
  galaxy_tags:
    - decidim
    - docker
    - democracy
    - participation
    - civic
    - community
    - self-hosted
  issue_tracker_url: https://s.infinito.nexus/issues
