csp:
  flags:
    script-src-elem:
      unsafe-inline: true
    style-src-attr:
      unsafe-inline: true
  whitelist: {}
domains:
  aliases: []
  canonical:
  - decidim.{{ DOMAIN_PRIMARY }}
status_codes:
  default:
  - 200
networks:
  local:
    subnet: 192.168.104.176/28
