domains:
  canonical:
  - audio.{{ DOMAIN_PRIMARY }}
  aliases: []
csp:
  flags:
    style-src-attr:
      unsafe-inline: true
  whitelist:
    font-src:
    - 'data:'
networks:
  local:
    subnet: 192.168.101.96/28
