---
- name: "include sys-svc-compose role"
  include_role:
    name: sys-svc-compose
  vars:
    compose_handlers_flush: false
    compose_repository_pull: false
    application_id: "svc-db-openldap"

- name: Create container network
  include_tasks: "{{ [playbook_dir, 'roles/sys-svc-compose/tasks/utils/network/create.yml' ] | path_join }}"
  vars:
    network_role_id: "{{ application_id }}"

- name: Copy OpenLDAP image files to instance dir
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ [ lookup('container', application_id, 'directories.instance'), item.dest ] | path_join }}"
    mode: "{{ item.mode }}"
  loop:
    - { src: "entrypoint.sh", dest: "entrypoint.sh", mode: "0755" }
    - { src: "healthcheck.sh", dest: "healthcheck.sh", mode: "0755" }
  loop_control:
    label: "{{ item.dest }}"

- name: "Flush compose handlers"
  meta: flush_handlers
