---
galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Checks Docker containers for unhealthy or exited states and alerts on any issues.
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  license: Infinito.Nexus Community License (Non-Commercial)
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - monitor
    - docker
    - containers
    - health
    - systemd
