FROM {{ XWIKI_IMAGE }}:{{ XWIKI_VERSION }}
RUN printf '%s\n' \
  'xwiki.superadmin=1' \
  'xwiki.superadminpassword={{ XWIKI_SUPERADMIN_PASSWORD }}' \
  >> /usr/local/tomcat/webapps/ROOT/WEB-INF/xwiki.cfg
