- name: "Load destruction roles"
  include_tasks: "./tasks/groups/{{ destruction_group }}-roles.yml"
  loop:
    - svc-opt # Load optimation services
  loop_control:
    loop_var: destruction_group
    label: "{{ destruction_group }}-roles.yml"

- name: "Finalize services"
  include_role:
    name: sys-service-terminator
