galaxy_info:
  author: Kevin Veen-Birchenbach
  description: Installs the Zoom video conferencing client via AUR on Arch Linux.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: Kevin Veen-Birchenbach Consulting & Coaching Solutions https://www.veen.world
  galaxy_tags:
    - zoom
    - video
    - conferencing
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
  platforms:
    - name: Archlinux
      versions:
        - all
