csp:
  flags:
    script-src-elem:
      unsafe-inline: true
    style-src-attr:
      unsafe-inline: true
  whitelist:
    font-src:
    - 'data:'
domains:
  canonical:
  - open.project.{{ DOMAIN_PRIMARY }}
  aliases: []
networks:
  local:
    subnet: 192.168.102.80/28
