logout:
  enabled: false
  shared: false
dashboard:
  enabled: true
  shared: true
matomo:
  enabled: true
  shared: true
css:
  enabled: true
  shared: true
# noqa: email
email:
  enabled: false
  shared: false
prometheus:
  enabled: true
  shared: true
navigator:
  ports:
    local:
      http: 8039
  lifecycle: pre-alpha
  min_storage: 1GB
  cpus: '0.2'
  mem_reservation: 128m
  mem_limit: 256m
  pids_limit: 256
