galaxy_info:
  author: Kevin Veen‑Birkenbach
  description: 'Role to provision an OpenResty container via Docker Compose.

    '
  license: Infinito.Nexus Community License (Non-Commercial)
  company: "Kevin Veen‑Birkenbach  \nConsulting & Coaching Solutions  \nhttps://www.veen.world\n"
  galaxy_tags:
    - openresty
    - nginx
    - docker
    - reverse_proxy
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
