galaxy_info:
  author: Kevin Veen-Birchenbach
  description: Federated chess server based on ActivityPub. Play and follow games across the Fediverse with verified rules and open identities.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: Kevin Veen-Birchenbach Consulting & Coaching Solutions https://www.veen.world
  galaxy_tags:
    - chess
    - federation
    - activitypub
    - social
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
  platforms:
    - name: Any
      versions:
        - all
dependencies: []
