csp:
  whitelist:
    script-src-elem:
    - https://*.clarity.ms/
    connect-src:
    - https://*.clarity.ms
    - 'data:'
    style-src-elem: []
    font-src: []
    frame-ancestors: []
  flags:
    style-src-attr:
      unsafe-inline: true
    script-src-elem:
      unsafe-inline: true
    script-src-attr:
      unsafe-eval: true
domains:
  canonical:
  - qr.{{ DOMAIN_PRIMARY }}
  aliases: []
networks:
  local:
    subnet: 192.168.104.64/28
