galaxy_info:
  author: Kevin Veen-Birchenbach
  description: Automates Firefox installation and enforces Enterprise Policies (auto-install extensions) on Arch Linux.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: Kevin Veen-Birchenbach Consulting & Coaching Solutions https://www.veen.world
  galaxy_tags:
    - firefox
    - enterprise-policy
    - browser
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
  platforms:
    - name: Archlinux
      versions:
        - rolling
dependencies: []
