ollama:
  enabled: false
  shared: true
  backup:
    no_stop_required: true
  image: ollama/ollama
  version: latest
  name: ollama
  min_storage: 20GB
  cpus: '4.0'
  mem_reservation: 6g
  mem_limit: 8g
  pids_limit: 2048
  ports:
    inter: 11434
  preload_models:
  - llama3:latest
  - mistral:latest
  - nomic-embed-text:latest
  lifecycle: beta
