---
- include_tasks: utils/once/flag.yml

- name: "Redirect {{ lookup('domain', 'web-svc-css') }} to web-svc-cdn"
  include_role:
    name: web-opt-rdr-domains
  vars:
    redirect_domain_mappings:
      - source: "{{ lookup('domain', 'web-svc-css') }}"
        target: "{{ lookup('domain', 'web-svc-cdn') }}"
