---
docker_compose_flush_handlers: false # Set to true in the vars/main.yml of the including role to autoflush after compose routine
compose_pull_repository: "{{ compose_repository_url is defined and compose_repository_url is string and compose_repository_url | length >
  0 }}"
COMPOSE_LOAD_SERVICES: true # Implemented to deploy roles during development faster by skipping dependencies
