galaxy_info:
  author: Kevin Veen-Birchenbach
  description: Deploys Let’s Encrypt certificates into Docker Compose Nginx setups via systemd service and timer.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: Kevin Veen-Birchenbach Consulting & Coaching Solutions https://www.veen.world
  galaxy_tags:
    - nginx
    - letsencrypt
    - docker
    - systemd
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: '2.9'
  platforms:
    - name: Any
      versions:
        - all
