domains:
  canonical:
  - kix.{{ DOMAIN_PRIMARY }}
  aliases: []
csp:
  flags:
    script-src-elem:
      unsafe-inline: true
    style-src-attr:
      unsafe-inline: true
networks:
  local:
    subnet: 192.168.105.80/28
