galaxy_info:
  author: Kevin Veen-Birkenbach
  description: 'Extends sys-stk-backend by adding an HTTP reverse proxy via sys-stk-front-proxy.

    '
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  license: Infinito.Nexus Community License (Non-Commercial)
  galaxy_tags:
    - docker
    - database
    - proxy
    - compose
  min_ansible_version: '2.9'
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
