csp:
  whitelist:
    connect-src: "{{ lookup('fediwall_active', 'url_bases') }}"
    img-src:
    - 'http:'
    - 'https:'
    - 'data:'
    media-src:
    - 'http:'
    - 'https:'
    - 'data:'
  flags:
    style-src-attr:
      unsafe-inline: true
    script-src-elem:
      unsafe-inline: true
    script-src-attr:
      unsafe-inline: true
domains:
  canonical:
  - fediwall.{{ DOMAIN_PRIMARY }}
  aliases: []
networks:
  local:
    subnet: 192.168.102.240/28
