mariadb:
  enabled: false
  shared: true
  version: latest
  image: mariadb
  name: mariadb
  min_storage: 10GB
  backup:
    database_routine: true
  cpus: '2.0'
  mem_reservation: 2g
  mem_limit: 4g
  pids_limit: 1024
  ports:
    local:
      database: 3306
  lifecycle: beta
