galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Pretix is an open-source ticketing system for events, enabling online sales, registration management, custom ticket layouts, and secure payment integration. It is self-hosted to ensure full control and data protection.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: 'Kevin Veen-Birkenbach

    Consulting & Coaching Solutions

    https://www.veen.world

    '
  galaxy_tags:
    - pretix
    - tickets
    - sales
    - shop
  issue_tracker_url: https://s.infinito.nexus/issues
dependencies: []
