---
# nocheck: dynamic-flag
logout:
  enabled: false
  shared: false
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
# nocheck: shared
# nocheck: dynamic-flag
redis:
  backup:
    disabled: true
  enabled: true
postgres:
  enabled: true # nocheck: dynamic-flag
  shared: "{{ 'svc-db-postgres' in group_names }}"
onlyoffice:
  enabled: true
  shared: true
  image: onlyoffice/documentserver
  version: latest
  name: onlyoffice
  min_storage: 20GB
  cpus: 2
  mem_reservation: 1g
  mem_limit: 4g
  pids_limit: 8192
  backup:
    no_stop_required: true
  ports:
    local:
      http: 8061
  lifecycle: beta
# nocheck: dynamic-flag
css:
  enabled: true
  shared: true
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
