---
galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Deploys Keycloak, an identity and access management solution providing single sign-on, federation, and centralized user management for the
    Infinito.Nexus stack.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  galaxy_tags:
    - keycloak
    - docker
    - identity management
    - sso
    - self-hosted
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
