---
csp:
  flags:
    script-src-elem:
      unsafe-inline: true
    script-src-attr:
      unsafe-inline: true
    style-src-attr:
      unsafe-inline: true
  whitelist:
    frame-src:
      - "*"
    frame-ancestors:
      - "{{ lookup('tls', 'web-app-keycloak', 'protocols.web') }}://*.{{ DOMAIN_PRIMARY }}"
domains:
  canonical:
    - auth.{{ DOMAIN_PRIMARY }}
  aliases: []
networks:
  local:
    subnet: 192.168.101.160/28
