# nocheck: dynamic-flag
# nocheck: logout
logout:
  enabled: false
  shared: false
ldap:
  enabled: true  # nocheck: dynamic-flag
  shared: "{{ 'svc-db-openldap' in group_names }}"
  sync:
    period:
      changes: 900
      full: 86400
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
email:
  enabled: "{{ 'web-app-mailu' in group_names }}"
  shared: "{{ 'web-app-mailu' in group_names }}"
keycloak:
  enabled: true
  shared: true
  provides: oidc
  covers:
  - oauth2
  image: quay.io/keycloak/keycloak
  version: latest
  name: keycloak
  min_storage: 5GB
  cpus: '2.0'
  mem_reservation: 2g
  mem_limit: 4g
  pids_limit: 1024
  realm:
    import_enabled: true
    totp_enabled: true
  users:
    emails_verified: true
  scopes:
    nextcloud: nextcloud
  accounts:
    bootstrap:
      username: administrator
    system:
      username: '{{ SOFTWARE_NAME | replace(''.'', ''_'') | lower }}'
  ports:
    local:
      http: 8032
  run_after:
  - web-app-matomo
  - web-app-mailu
  lifecycle: beta
postgres:
  enabled: true  # nocheck: dynamic-flag
  shared: "{{ 'svc-db-postgres' in group_names }}"
# nocheck: dynamic-flag
css:
  enabled: true
  shared: true
# nocheck: dynamic-flag
recaptcha:
  enabled: '{{ RECAPTCHA_ENABLED | bool }}'
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
