galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Snipe‑IT is an open‑source asset management system providing a containerized deployment with centralized MariaDB integration, configurable SMTP settings, and pending SAML authentication enhancements for secure asset tracking and management.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: "Kevin Veen-Birkenbach  \nConsulting & Coaching Solutions  \nhttps://www.veen.world\n"
  min_ansible_version: '2.9'
  platforms:
    - name: Linux
      versions:
        - all
  galaxy_tags:
    - snipe-it
    - asset-management
  issue_tracker_url: https://s.infinito.nexus/issues
dependencies: []
