server:
  domains:
    canonical:
      - "cdn.{{ DOMAIN_PRIMARY }}"
    aliases: []
compose:
  services:
    dashboard:
      enabled: false
    matomo:
      enabled: true
      shared: true
    css:
      enabled: false
      shared: true
    javascript:
      enabled: false
      shared: true
    prometheus:
      enabled: true
      shared: true
