---
- name: "Ensure docker network for '{{ network_role_id }}' exists"
  community.docker.docker_network:
    name: "{{ network_role_id | get_entity_name }}"
    state: present
    labels:
      com.docker.compose.network: "default"
      com.docker.compose.project: "{{ network_role_id | get_entity_name }}"
    ipam_config:
      - subnet: "{{ lookup('config', network_role_id, 'server.networks.local.subnet') }}"
