FROM "{{ CONFLUENCE_IMAGE }}:{{ CONFLUENCE_VERSION }}"

# Optional: install OIDC SSO app (example path/name)
# COPY ./plugins/atlassian-sso-dc-latest.obr /opt/atlassian/confluence/confluence/WEB-INF/atlassian-bundled-plugins/

# Ensure proper permissions for app data
RUN mkdir -p {{ CONFLUENCE_HOME }} && \
    chown -R 2001:2001 {{ CONFLUENCE_HOME }}
RUN printf "confluence.home={{ CONFLUENCE_HOME }}\n" \
  > /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties
