FROM "{{ CONFLUENCE_IMAGE }}:{{ CONFLUENCE_VERSION }}"

# Optional: install OIDC SSO app (example path/name)
# COPY ./plugins/atlassian-sso-dc-latest.obr /opt/atlassian/confluence/confluence/WEB-INF/atlassian-bundled-plugins/

# Ensure proper permissions for app data
RUN mkdir -p /var/atlassian/application-data/confluence && \
    chown -R 2001:2001 /var/atlassian/application-data/confluence